name: Workflow Sync

on:
  push:
    branches: [ main ]

jobs:
  update-ref:
    runs-on: ubuntu-20.04
    steps:
      - name: Update ref
        # todo: not sure if this will actually guard against concurrent pushes to main.
        # worst case, workflow might be a commit-out-of-sync
        if: github.ref == 'refs/heads/main'
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "heads/workflow",
              sha: context.sha
            })
